minor update

diff --git a/docker/sys_img/Dockerfile b/docker/sys_img/Dockerfile
--- a/docker/sys_img/Dockerfile
+++ b/docker/sys_img/Dockerfile
@@ -12,6 +12,8 @@ RUN apt-get update \
         initramfs-tools \
         ubuntu-minimal \
         grub-efi-$TARGETARCH \
+        linux-image-5.19.0-50-generic \
+        efibootmgr \
         systemd \
         systemd-sysv \
         libsystemd0 \
@@ -29,19 +31,19 @@ RUN apt-get update \
 
 # Install Docker
 RUN --mount=type=cache,id=apt-cache$TARGETARCH,sharing=locked,target=/var/cache/apt --mount=type=cache,id=apt-lib-$TARGETARCH,sharing=locked,target=/var/lib/apt \
-    apt-get update \
-    && apt-get install -y curl \
-    && curl -fsSL https://get.docker.com -o get-docker.sh  \
-    && sh get-docker.sh --version 28.5.1
-
-RUN set -eux; \
+    set -eux; \    
+    apt-get update; \
+    apt-get install -y curl \
+    curl -fsSL https://get.docker.com -o get-docker.sh; \
+    sh get-docker.sh --version 28.5.1; \
     . /etc/os-release; \ 
-     if [ -z "${VERSION_ID:-}" ] || [ -z "${VERSION_CODENAME:-}" ]; then \ 
-         echo "Unable to detect Ubuntu version metadata"; exit 1; \ 
-     fi; \ 
-     apt-get update; \ 
-     apt-get install -y --allow-downgrades "containerd.io=1.7.28-1~ubuntu.${VERSION_ID}~${VERSION_CODENAME}" && \ 
-     apt-mark hold containerd.io 
+    if [ -z "${VERSION_ID:-}" ] || [ -z "${VERSION_CODENAME:-}" ]; then \ 
+        echo "Unable to detect Ubuntu version metadata"; exit 1; \ 
+    fi; \ 
+    apt-get update; \ 
+    apt-get install -y --allow-downgrades "containerd.io=1.7.28-1~ubuntu.${VERSION_ID}~${VERSION_CODENAME}" && \ 
+    apt-mark hold containerd.io; \
+    apt-get clean;
 
 # Disable systemd services/units that are unnecessary within a container.
 RUN systemctl mask systemd-udevd.service \
