tests: for test

diff --git a/docker/app_img/Dockerfile b/docker/app_img/Dockerfile
--- a/docker/app_img/Dockerfile
+++ b/docker/app_img/Dockerfile
@@ -8,39 +8,37 @@ COPY ./${OTACLIENT_WHL} /tmp
 ARG OTACLIENT_INSTALLATION="/otaclient"
 ENV OTACLIENT_VENV=${OTACLIENT_INSTALLATION}/venv
 
-RUN set -eux; \
-    apt-get update -qq; \
-    apt-get install --no-install-recommends -y \
-        software-properties-common; \
-    add-apt-repository ppa:deadsnakes/ppa; \
-    apt-get update -qq; \
+RUN set -eux && \
+    apt-get update -qq && \
+    apt-get install --no-install-recommends -y software-properties-common && \
+    add-apt-repository ppa:deadsnakes/ppa && \
+    apt-get update -qq && \
     apt-get install --no-install-recommends -y \
         python3.8 \
         python3.8-venv \
         python3.8-distutils \
-        python3-pip; \
-    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1; \
-    update-alternatives --set python3 /usr/bin/python3.8; \
-    python3 --version; \
-    # setup virtual env
-    mkdir -p ${OTACLIENT_VENV}; \
-    cd ${OTACLIENT_INSTALLATION}; \
-    python3 -m venv ${OTACLIENT_VENV}; \
-    . ${OTACLIENT_VENV}/bin/activate; \
-    # install otaclient
-    python3 -m pip install -U pip; \
-    python3 -m pip install /tmp/${OTACLIENT_WHL}; \
-    # cleanup
-    apt-get clean; \
-    \
-    # NOTE: copy from docker official python3 dockerfile
-	find ${OTACLIENT_VENV} -depth \
-		\( \
-			\( -type d -a \( -name test -o -name tests -o -name idle_test -o -name __pycache__ \) \) \
-			-o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name 'libpython*.a' \) \) \
-		\) -exec rm -rf '{}' + \
-	; \
-	\
+        python3-pip && \
+    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 && \
+    update-alternatives --set python3 /usr/bin/python3.8 && \
+    python3 --version
+
+# Setup venv and install otaclient
+RUN set -eux && \
+    mkdir -p ${OTACLIENT_VENV} && \
+    cd ${OTACLIENT_INSTALLATION} && \
+    python3 -m venv ${OTACLIENT_VENV} && \
+    . ${OTACLIENT_VENV}/bin/activate && \
+    python3 -m pip install -U pip && \
+    python3 -m pip install /tmp/${OTACLIENT_WHL}
+
+# Cleanup
+RUN set -eux && \
+    apt-get clean && \
+    find ${OTACLIENT_VENV} -depth \
+        \( \
+            \( -type d -a \( -name test -o -name tests -o -name idle_test -o -name __pycache__ \) \) \
+            -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name 'libpython*.a' \) \) \
+        \) -exec rm -rf '{}' + && \
     rm -rf \
         /root/.cache \
         /tmp/* \
